version: '3.9'

services:
  db:
    image: postgres:15
    container_name: contacts-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    volumes:
      - extension_postgres_data:/var/lib/postgresql/data

  backend:
    container_name: contacts-backend
    build: .
    command: sh -c "npx prisma migrate deploy && npm run dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/contacts
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  extension_postgres_data:
