version: '3.9'

services:
  db:
    image: postgres:15
    container_name: contacts-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    volumes:
      - extension_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: contacts-redis
    restart: always
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - extension_redis_data:/data  # Redis data persistence

  backend:
    container_name: contacts-backend
    build: .
    command: sh -c "npx prisma migrate deploy && npm run dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/contacts
      REDIS_HOST: redis  # Use the Redis service name as host
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis

volumes:
  extension_postgres_data:
  extension_redis_data:
